name: Deploy to Cloud Run Jobs

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: tysa-491218
  REGION: us-central1
  JOB_NAME: sync-gocanvas-job

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # 1. Autenticar GitHub con GCP
      - name: Auth GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # 2. Configurar Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 3. Configurar Docker para Artifact Registry
      - name: Configure Docker Auth
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      # 4. Construir y empujar imagen
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=$REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$JOB_NAME:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # 5. Desplegar Cloud Run Job con GOCANVAS_PASSWORD agregado
      - name: Deploy Cloud Run Job
        run: |
          IMAGE_NAME=$REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$JOB_NAME:${{ github.sha }}
          gcloud run jobs deploy $JOB_NAME \
            --image $IMAGE_NAME \
            --region $REGION \
            --set-env-vars GOCANVAS_API_KEY=${{ secrets.GOCANVAS_API_KEY }},FORM_ID=${{ secrets.FORM_ID }},NOMBRE_DEL_SHEET="${{ secrets.NOMBRE_DEL_SHEET }}",GOCANVAS_PASSWORD=${{ secrets.GOCANVAS_PASSWORD }}